[workspace]
members = [
    "proto",
    "core",
    "local",
    "remote",
    "balancer",
    "server",
    "grabber-client",
]
resolver = "2"

[profile.release]
lto = "thin"
codegen-units = 16
panic = "abort"
opt-level = 3
