[package]
name = "sfu-core"
version = "0.1.0"
edition = "2024"

[dependencies]
sfu-proto = { path = "../proto" }

async-trait = "0.1"
anyhow = "1"
webrtc = "0.14.0"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["sync"] }
