[package]
name = "sfu-remote"
version = "0.1.0"
edition = "2024"

[dependencies]
sfu-core = { path = "../core" }
sfu-proto = { path = "../proto" }

tonic = "0.10"
async-trait = "0.1"
anyhow = "1.0"
tokio = { version = "1" }
tracing = "0.1"


