[package]
name = "balancer"
version = "0.1.0"
edition = "2024"

[dependencies]
sfu-core = { path = "../core" }

tokio = { version = "1", features = ["time"] }
arc-swap = "1.6"
tracing = "0.1"
anyhow = "1.0"
rand = "0.8"
