server:
  bind_address: "0.0.0.0:5000"
  enable_metrics: true

ice_servers:
  - "stun:stun.l.google.com:19302"

codecs:
  audio:
    - mime: "audio/opus"
      payload_type: 111
      clock_rate: 48000
      channels: 2
      sdp_fmtp: "minptime=10;useinbandfec=1"

  video:
    - mime: "video/VP8"
      payload_type: 96
      clock_rate: 90000

    - mime: "video/H264"
      payload_type: 102
      clock_rate: 90000
      sdp_fmtp: "level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f"
